# DataSource Config
spring:
  profiles:
    active: default
  application:
    name: wow
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://67.207.80.139:3306/wow?characterEncoding=utf-8&userSSL=false
    username: root
    password: 123456a
  redis:
    database: 0
    #host: 127.0.0.1
    host: 127.0.0.1
    port: 6379
    password: 123456a
    timeout: 1000
    jedis:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 8
        min-idle: 0
#  rabbitmq:
#    host: 67.207.80.139
#    #  rabbitmq主服务端口为5672,管理页面端口为15672
#    port: 5672
#    username: admin
#    password: 123456a
#    #   设置回调函数
#    #   confirm-type: 默认为None即不启用，
#    #    correlated: 发布消息成功或失败到达交换机时触发回调方法
#    #    simple: 具有两个功能
#    #    1.与correlated相同
#    #    2.可以使用rabbittemplate调用waitforconfirm或waitForConfirmsOrDie
#    #     等待broker节点返回发送结果，根据结果来判定下一步逻辑
#    publisher-confirm-type: correlated
#    publisher-returns: true

swagger:
  enable: true
  application-name: ${spring.application.name}
  application-version: 1.0
  application-description: Swagger 3.0 for WOW backend
  try-host: http://localhost:${server.port}
jwt:
  header: "Authorization" #token返回头部
  tokenPrefix: "Bearer " #token前缀
  secret: "qwertyuiop7418520" #密钥
  expireTime: 60 #token有效时间 (分钟) 建议一小时以上
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:mapper/*.xml

---
server:
  port: 8080
spring:
  config:
    activate:
      on-profile: default
---
server:
  port: 8083
spring:
  config:
    activate:
      on-profile: zmh

---
server:
  port: 8086
spring:
  config:
    activate:
      on-profile: zz
